exports.STATUS_NEW = "NEW";
exports.STATUS_ACCEPTED = "ACCEPTED";
exports.STATUS_REJECTED = "REJECTED";
exports.STATUS_READY = "READY";
exports.STATUS_DELIVERING = "DELIVERING";
exports.STATUS_COMPLETED = "COMPLETED";
